version: '2'

services:
    api:
        build: .
        command: >
          gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            "mta_tracker.app:create_app()"
        env_file:
            - '.env'
        volumes:
            - '.:/mta_tracker'
        ports:
            - '8000:8000'
